import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';

import { CustomLayout } from '@/components/layout/CustomLayout';

import '../assets/styles/globals.scss';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: [
		{
			url: '/images/favicon.svg',
			href: '/images/favicon.svg',
		},
	],
};

async function getTheme() {
	const theme = cookies().get('theme')?.value;
	if (!theme) {
		return 'normal';
	}
	return theme;
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const theme = await getTheme();

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased ${theme}`}>
				<CustomLayout>{children}</CustomLayout>
			</body>
		</html>
	);
}
