import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import { Toaster } from 'sonner';

import '../assets/styles/globals.scss';

import { QueryProvider } from '@/providers/query-provider';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: [
		{
			url: '/images/favicon.svg',
			href: '/images/favicon.svg',
		},
	],
};

async function getTheme() {
	const theme = cookies().get('theme')?.value;
	if (!theme) {
		return null;
	}
	return theme;
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const theme = await getTheme();

	return (
		<html lang="en">
			<body
				className={`transition duration-700 ${geistSans.variable} ${geistMono.variable} antialiased ${theme}`}>
				<Toaster
					richColors
					position="top-center"
				/>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
